### ISSUE TITLE
请问这个js要怎么运行在安卓手机上

### ISSUE THREAD

**Issue by DancingLeaf123** [neoshua/dingdongqiangcai#1]

**Comment by neoshua** [comment]
请参考hamibot教程



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月9日(周六) 上午10:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [neoshua/dingdongqiangcai] 请问这个js要怎么运行在安卓手机上 (Issue #1)
